### PR TITLE
Feature/defer client evaluation

### PR DESCRIPTION
**Pull request by luke-hill**
This uses some clever ruby to defer (lazily), evaluate some of the "core" workings of mailosaur.

The first 3 commits of this PR are copies of my other branch, and I'll rebase once that's merged in.

If the last commit is confusing I'm happy to remove it (Some people aren't used to `#tap`)

### CODE REVIEW

**Comment by hippyhorse** [comment]
Closing as should be resolved by PR #27

**Comment by luke-hill** [comment]
Just for reference this PR isn't fixed by #27

#27 is implementing rubocop, this is deferring evaluation to make the entire code-base run a lot quicker for people only quering a portion.

**Comment by hippyhorse** [comment]
Sorry about that @luke-hill - feel free to reopen this with the current master merged

**Comment by luke-hill** [comment]
You'll need to re-open this as I cannot. I've removed all un-required commits and rebased ontop of the latest master.

Feel free to re-review now.

**Comment by luke-hill** [comment]
Superseded by #28

**Pull request closed without merging**
